SportsStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    public class NavController : Controller
    {
  
        private IProductsRepository repository;
        private ICategoryRepository catRepository;

        //Constructor
        public NavController(IProductsRepository repo, ICategoryRepository cat)
        {
            repository = repo;
            catRepository = cat;
        }

        //Navigation for Sidebar, referenced by "Model" in the Sidebar.cshtml page.
        public PartialViewResult Sidebar(string category)
        {
            CategoryListModel model = new CategoryListModel
            {

                Categories = catRepository.Categories
                .Where(c => category == c.ParentName)

            };

         

            return PartialView(model);
        }

        //Navigation for TopBar
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(categories);
        }

    }
}

SportsStore.WebUI/Views/Shared/CategorySummary.cshtml
@model SportsStore.Domain.Entities.Categories

@{
    int id = Model.CategoryID;
    var name = Model.CategoryName;

}


 @Html.RouteLink(name, new{
    controller = "Product",
    action = "List",
    id = id,
    name = name
})

SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product

@{
    int id = Model.ProductID;
    var name = Model.Name;
    var description = Model.Description;
    decimal price = Model.Price;
    var image = Url.Content("~/Content/img/products/" + id + ".jpg");
    
    //var image = "/Content/img/products/" + id + ".jpg";
}



<div class="row">
<div class="col-lg-2"><img src="@Url.Content("~/Content/img/products/" + id + ".jpg")" class="img-responsive" /></div>
<div class="col-lg-8">
  <h3> @Html.RouteLink(name, new{
    controller = "Product",
    action = "ProductDetail",
    id = id,
    product = name,
    description = description,
    price = price
    
}) </h3>


    
  
    @using(Html.BeginForm("AddToCart", "Cart")){
        @Html.HiddenFor(x => x.ProductID)
        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
       
        <input class="btn btn-default pull-right" type="submit" value="+ Add to cart" />
    }
    <h4>@Model.Price.ToString("c")</h4>
    </div>

</div>
<hr />

SportsStore.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/Content/style.css" rel="stylesheet">
    <link href="~/Content/font-awesome.min.css" rel="stylesheet">
<link href="∼/Content/bootstrap-theme.css" rel="stylesheet" />
<link href="∼/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!--<link href="~/Content/Site.css" type="text/css" rel="stylesheet" />->
            <!-- Bootstrap core CSS -->
 
    @Styles.Render("~/Content/themes/style/css")
    @Styles.Render("~/Content/css")
   
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html">GameStore</a>
        </div>
        <div class="navbar-collapse collapse navbar-right">
          <ul class="nav navbar-nav">
            <li>@Html.ActionLink("HOME", "Index", "Home")</li>
     
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">SHOP <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li>@{ Html.RenderAction("Menu", "Nav"); }</li>
              </ul>
            </li>
            <li> @{Html.RenderAction("Summary", "Cart");}</li>
             <li></li>
          </ul>
            <div class="col-sm-3 pull-right">
                @using (Html.BeginForm ("Search","Product",FormMethod.Get ))
                {
            @Html.TextBox("query", null, new { @class = "form-control" });
                
                <input class="btn btn-
                     pull-right" type="submit" value="Search" />
 }
            </div>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div id="blue">
	    <div class="container">
			<div class="row">
				<h3>@ViewBag.Title</h3>
			</div><!-- /row -->
	    </div> <!-- /container -->
	</div><!-- /blue -->

    <div class="container well well-lg">
	 	<div class="row">
             <! -- SIDEBAR -->
	 	<!--	<div class="col-lg-2">
                 
                     <ul class="sidebar-nav">
                         <li class="sidebar-brand">
                  
                             </li>
                         </ul>
                    
            </div> -->
             
                 @RenderBody()
             
        </div>
       </div>


   

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
        <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    @Scripts.Render("~/bundles/js")
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    

</body>
</html>